In [3]:
import numpy as np

In [24]:
A = np.array([[3,6,7],[5,-3,0]])

In [25]:
AA = np.array([[3,2,7],[5,1,1]])

In [26]:
B = np.array([[1,1],[2,1],[3,-3]])

In [34]:
product = A.dot(B)
product

array([[ 36, -12],
       [ -1,   2]])

In [28]:
substraction = A - AA
substraction = np.subtract(A,AA)
substraction

array([[ 0,  4,  0],
       [ 0, -4, -1]])

In [29]:
addition = A + AA
addition = np.add(A,AA)
addition

array([[ 6,  8, 14],
       [10, -2,  1]])

In [30]:
division = A / AA
division = np.divide(A,AA)
division

array([[ 1.,  3.,  1.],
       [ 1., -3.,  0.]])

In [35]:
product = A * B
product = multiply(A, B)
product

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [36]:
np.exp(A)

array([[2.00855369e+01, 4.03428793e+02, 1.09663316e+03],
       [1.48413159e+02, 4.97870684e-02, 1.00000000e+00]])

In [37]:
A.min()

-3

In [38]:
A.mean()

3.0

In [49]:
A.sort()

In [53]:
for i in range(0,10,2):
        if i % 2 == 0:
            print(i)
            i = i + 4
            print("H",i)
            

0
H 4
2
H 6
4
H 8
6
H 10
8
H 12


In [ ]:
 i = 0

    while i < len(ar) - 1:
        if ar[i] == ar[i+1]:
            print("*",i," ",i+1," ",ar[i]," ",ar[i+1])
            count = count + 1
            i = i + 2
        else:
            i = i + 1

In [46]:
print(ordenado)

None
